# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "59714fb2f34b0aed7d15464b3623fe9d"
name = "checkout-banner-extension"
handle = "checkout-banner-extension-4"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "euribe-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
